### ISSUE TITLE
bank 0 and 1 overlap?

### ISSUE THREAD

**Issue by Bashinerox** [Dooskington/GameLad#108]
It looks like bank1 is starting at the wrong address. the else prevents it from being an actual bug, unless you ever remove the else clause...

```
if (address >= 0xC000 && address <= 0xCFFF)
    {
        return m_bank0[address - 0xC000];
    }
    else if (address >= 0xC000 && address <= 0xDFFF) // <== bank 1 is starting at 0xC000 instead of 0xD000
    {
        return m_bank1[address - 0xD000];
    }
```

**Comment by Dooskington** [comment]
Ooh. Nice catch.

As you pointed out this doesn't cause any issues, but I'll probably get in there and fix this next time I get a chance.
